const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const CORS={"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,PUT,DELETE,OPTIONS","access-control-allow-headers":"content-type,x-admin-password"};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...CORS}})}
function authed(request,env){const p=request.headers.get("x-admin-password")||"";return !!env.ADMIN_PASSWORD&&p===env.ADMIN_PASSWORD}
function safeKey(){return `${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}`}
async function parsePost(request){const b=await request.json();if(!b.title||!b.category||!b.section||!Array.isArray(b.blocks)||!b.blocks.length)throw new Error("Не заполнены обязательные поля.");return {title:String(b.title).trim().slice(0,200),category:String(b.category),section:String(b.section),excerpt:String(b.excerpt||"").slice(0,1000),image:String(b.image||"").slice(0,2000),blocks:b.blocks.map(x=>({heading:String(x.heading||"").slice(0,200),text:String(x.text||"").slice(0,20000)})).filter(x=>x.heading||x.text)}}
export default{async fetch(request,env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{headers:CORS});
  if(url.pathname==="/api/posts"&&request.method==="GET"){const {results}=await env.DB.prepare("SELECT id,title,category,section,excerpt,image,blocks,created_at FROM posts ORDER BY created_at DESC").all();return json((results||[]).map(p=>({...p,blocks:JSON.parse(p.blocks||"[]")})))}
  if(url.pathname==="/api/admin/check"&&request.method==="POST")return json({ok:authed(request,env)},authed(request,env)?200:401);
  if(url.pathname==="/api/upload"&&request.method==="POST"){if(!authed(request,env))return json({error:"Unauthorized"},401);if(!env.IMAGE_BUCKET)return json({error:"R2 ещё не подключён."},503);const form=await request.formData();const file=form.get("image");if(!(file instanceof File))return json({error:"Файл не найден."},400);if(file.size>8*1024*1024)return json({error:"Файл больше 8 МБ."},413);const allowed=["image/jpeg","image/png","image/webp","image/gif"];if(!allowed.includes(file.type))return json({error:"Разрешены JPG, PNG, WEBP и GIF."},415);const ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif"}[file.type];const key=`${safeKey()}.${ext}`;await env.IMAGE_BUCKET.put(key,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:"public, max-age=31536000, immutable"}});return json({ok:true,key,url:`/media/${key}`})}
  if(url.pathname.startsWith("/media/")&&request.method==="GET"){if(!env.IMAGE_BUCKET)return new Response("R2 not configured",{status:503});const key=decodeURIComponent(url.pathname.slice(7));const obj=await env.IMAGE_BUCKET.get(key);if(!obj)return new Response("Not found",{status:404});const h=new Headers();obj.writeHttpMetadata(h);h.set("etag",obj.httpEtag);h.set("cache-control","public, max-age=31536000, immutable");return new Response(obj.body,{headers:h})}
  if(url.pathname==="/api/posts"&&request.method==="POST"){if(!authed(request,env))return json({error:"Unauthorized"},401);try{const b=await parsePost(request);const id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO posts (id,title,category,section,excerpt,image,blocks,created_at) VALUES (?,?,?,?,?,?,?,datetime('now'))`).bind(id,b.title,b.category,b.section,b.excerpt,b.image,JSON.stringify(b.blocks)).run();return json({ok:true,id})}catch(e){return json({error:e.message||"Ошибка"},400)}}
  if(url.pathname.startsWith("/api/posts/")&&(request.method==="PUT"||request.method==="DELETE")){if(!authed(request,env))return json({error:"Unauthorized"},401);const id=decodeURIComponent(url.pathname.slice("/api/posts/".length));if(request.method==="DELETE"){await env.DB.prepare("DELETE FROM posts WHERE id=?").bind(id).run();return json({ok:true})}try{const b=await parsePost(request);await env.DB.prepare("UPDATE posts SET title=?,category=?,section=?,excerpt=?,image=?,blocks=? WHERE id=?").bind(b.title,b.category,b.section,b.excerpt,b.image,JSON.stringify(b.blocks),id).run();return json({ok:true})}catch(e){return json({error:e.message||"Ошибка"},400)}}
  return env.ASSETS.fetch(request)}};
